"""Codegen: turn a compiled IR into a POD C++ header of ``constexpr`` coefficient tables.

The emitted header is the only thing the real-time engine sees of the compiler — no JSON is
parsed on the audio path. Output lands in ``nodes/generated/`` (a build artifact, gitignored)
and is consumed by ``BiquadNode`` / the Tube Screamer module.
"""

from __future__ import annotations

from .ir import (
    BiquadParamTable,
    CircuitIR,
    Oversample,
    ParamSpec,
    Skew,
    Waveshaper,
    iter_biquads,
    iter_waveshapers,
)


def _f(x: float) -> str:
    s = f"{x:.9g}"
    # A float literal needs a '.' or exponent; "0", "51000", "1" would be ill-formed with 'f'.
    if not any(c in s for c in ".eEnN"):
        s += ".0"
    return s + "f"


def _rate_token(rate: float) -> str:
    return str(int(round(rate)))


def _skew_token(skew: Skew) -> str:
    return "ParamSkew::Logarithmic" if skew is Skew.logarithmic else "ParamSkew::Linear"


def _emit_param(table_id: str, p: ParamSpec, out: list[str]) -> None:
    out.append(f"inline ParameterDesc {table_id}Param() {{")
    out.append("    return ParameterDesc{")
    out.append(f'        "{p.id}", {_f(p.min)}, {_f(p.max)}, {_f(p.default_proportion)},')
    smoothing = _f(p.smoothing_seconds)
    out.append(f"        {_skew_token(p.skew)}, {_f(p.skew_midpoint)}, {smoothing}}};")
    out.append("}")


def _emit_biquad(table: BiquadParamTable, out: list[str]) -> None:
    tid = table.id
    n = len(table.param_axis)
    out.append(f"// --- {tid} biquad ({n} rows) ---")
    out.append(f"inline constexpr int {tid}_rows = {n};")
    axis = ", ".join(_f(v) for v in table.param_axis)
    out.append(f"inline constexpr float {tid}_axis[{n}] = {{{axis}}};")
    for rate in table.rates:
        tok = _rate_token(rate.sample_rate)
        out.append(f"inline constexpr BiquadSection {tid}_sections_{tok}[{n}] = {{")
        for s in rate.sections:
            out.append(f"    {{{_f(s.b0)}, {_f(s.b1)}, {_f(s.b2)}, {_f(s.a1)}, {_f(s.a2)}}},")
        out.append("};")
        out.append(
            f"inline constexpr BiquadCoeffTable {tid}_table_{tok}"
            f"{{{tid}_axis, {tid}_sections_{tok}, {n}, {rate.sample_rate:.1f}}};"
        )
    out.append(f"inline const BiquadCoeffTable* {tid}Table(double sampleRate) noexcept {{")
    out.append("    const long long hz = static_cast<long long>(sampleRate + 0.5);")
    for rate in table.rates:
        tok = _rate_token(rate.sample_rate)
        out.append(f"    if (hz == {tok}) return &{tid}_table_{tok};")
    out.append("    return nullptr;")
    out.append("}")
    _emit_param(tid, table.param, out)


def _emit_waveshaper(s: Waveshaper, out: list[str]) -> None:
    out.append(f"// --- {s.id} waveshaper ({s.kind}) ---")
    out.append(f"inline constexpr float {s.id}_saturation_current = {_f(s.saturation_current)};")
    out.append(f"inline constexpr float {s.id}_thermal_voltage = {_f(s.thermal_voltage)};")
    out.append(f"inline constexpr float {s.id}_r2_const = {_f(s.r2_const)};")
    out.append(f"inline constexpr float {s.id}_r2_pot = {_f(s.r2_pot)};")


def emit_header(ir: CircuitIR, namespace: str = "ts9") -> str:
    biquads = list(iter_biquads(ir.stages))
    shapers = list(iter_waveshapers(ir.stages))
    out: list[str] = [
        "#pragma once",
        "",
        f"// Generated by circuitc from circuit '{ir.name}' (ir_version {ir.ir_version}).",
        "// Do not edit: regenerate with `circuitc compile`.",
        "",
        '#include "tonestack/Parameter.h"',
        '#include "tonestack/nodes/BiquadCoeffs.h"',
        "",
        f"namespace tonestack::nodes::generated::{namespace} {{",
        "",
        f"inline constexpr int oversample_factor = "
        f"{next((s.factor for s in ir.stages if isinstance(s, Oversample)), 1)};",
        "",
    ]
    for table in biquads:
        _emit_biquad(table, out)
        out.append("")
    for shaper in shapers:
        _emit_waveshaper(shaper, out)
        out.append("")
    out.append(f"}} // namespace tonestack::nodes::generated::{namespace}")
    out.append("")
    return "\n".join(out)
